<?php

$this->layout('main', [
    'title' => __('Stereo Tool Configuration'),
    'manual' => true
]);
?>

<div class="card">
    <div class="card-header bg-primary-dark">
        <h2 class="card-title"><?=__('Stereo Tool Configuration')?></h2>
    </div>

    <div class="card-body">
        <div class="row">
            <?=$this->fetch('system/form_edit', ['form' => $form])?>
        </div>
    </div>
</div>
