<?php
/**
 * @var string|null $title
 * @var string|null $header
 * @var \App\Assets $assets
 * @var \App\Form\Form $form
 */

$this->layout('main', [
    'title' => $title,
    'header' => $header,
    'manual' => true,
]);
?>

<div class="card">
    <div class="card-header bg-primary-dark">
        <h2 class="card-title"><?=$title?></h2>
    </div>
    <div class="card-body">
        <div class="row">
            <?=$this->fetch('system/form_edit', ['form' => $form])?>
        </div>
    </div>
</div>
